<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$user=require_permission('agenda.view');\App\Core\Tenant::enforceActive((int)$user['tenant_id']);
$t=(int)$user['tenant_id'];$view=$_GET['view']??'week';$date=$_GET['date']??date('Y-m-d');
if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))$date=date('Y-m-d');
$base=new DateTimeImmutable($date);$from=$base;$to=$base;
if($view==='month'){$from=$base->modify('first day of this month');$to=$base->modify('last day of this month');}
elseif($view==='day'){$from=$to=$base;}else{$view='week';$from=$base->modify('monday this week');$to=$from->modify('+6 days');}
$sql="SELECT a.*,p.name patient_name,p.phone,u.name professional_name FROM appointments a JOIN patients p ON p.id=a.patient_id AND p.tenant_id=a.tenant_id JOIN users u ON u.id=a.professional_id AND u.tenant_id=a.tenant_id WHERE a.tenant_id=:t AND a.starts_at>=:from AND a.starts_at<DATE_ADD(:to,INTERVAL 1 DAY)";$params=['t'=>$t,'from'=>$from->format('Y-m-d'),'to'=>$to->format('Y-m-d')];
if(in_array($user['role_slug'],['psychologist','supervised'],true)){$sql.=' AND a.professional_id=:u';$params['u']=$user['id'];}
$status=$_GET['status']??'';if(in_array($status,['pending','confirmed','completed','cancelled','no_show'],true)){$sql.=' AND a.status=:s';$params['s']=$status;}$sql.=' ORDER BY a.starts_at';$st=db()->prepare($sql);$st->execute($params);$items=$st->fetchAll();
layout('Agenda',function()use($items,$from,$to,$date,$view,$status,$user){?>
<div class="page-head"><div><span class="eyebrow">Agenda clínica</span><h1><?=e($from->format('d/m/Y'))?><?= $from!=$to?' — '.e($to->format('d/m/Y')):''?></h1><p>Visão <?=$view==='day'?'diária':($view==='month'?'mensal':'semanal')?> com confirmação pública por token.</p></div><div class="split-actions"><a class="button ghost" href="<?=e(url('agenda/ical.php'))?>">Exportar iCal</a><?php if(\App\Core\Rbac::allows((int)$user['id'],'agenda.manage')):?><a class="button" href="<?=e(url('agenda/new.php'))?>">+ Agendar</a><?php endif?></div></div>
<div class="card"><div class="split-actions" style="margin-bottom:16px"><a class="button <?= $view==='day'?'':'ghost'?> small" href="?view=day&date=<?=e($date)?>">Dia</a><a class="button <?= $view==='week'?'':'ghost'?> small" href="?view=week&date=<?=e($date)?>">Semana</a><a class="button <?= $view==='month'?'':'ghost'?> small" href="?view=month&date=<?=e($date)?>">Mês</a><form method="get" class="split-actions"><input type="hidden" name="view" value="<?=e($view)?>"><input type="date" name="date" value="<?=e($date)?>"><select name="status"><option value="">Todos os status</option><?php foreach(['pending'=>'Pendente','confirmed'=>'Confirmado','completed'=>'Concluído','cancelled'=>'Cancelado','no_show'=>'Falta'] as $k=>$v):?><option value="<?=$k?>" <?=$status===$k?'selected':''?>><?=$v?></option><?php endforeach?></select><button class="button secondary small">Filtrar</button></form></div>
<div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Paciente</th><th>Profissional</th><th>Status</th><th>Local</th><th>Ação</th></tr></thead><tbody><?php if(!$items):?><tr><td colspan="6" class="muted">Nenhum atendimento no período.</td></tr><?php endif?><?php foreach($items as $a):?><tr><td><?=e(date('d/m H:i',strtotime($a['starts_at'])))?></td><td data-private><?=e($a['patient_name'])?></td><td><?=e($a['professional_name'])?></td><td><span class="status <?=e($a['status'])?>"><?=e($a['status'])?></span></td><td><?=e($a['modality']==='online'?'On-line':'Presencial')?></td><td><?php if(\App\Core\Rbac::allows((int)$user['id'],'agenda.manage')):?><form method="post" action="<?=e(url('agenda/status.php'))?>" class="split-actions"><?=csrf_field()?><input type="hidden" name="id" value="<?=$a['id']?>"><select name="status"><option value="confirmed">Confirmar</option><option value="completed">Concluir</option><option value="no_show">Falta</option><option value="cancelled">Cancelar</option></select><button class="button ghost small">Atualizar</button></form><?php endif?></td></tr><?php endforeach?></tbody></table></div></div>
<?php },['active'=>'agenda']);
