<?php
declare(strict_types=1);
require dirname(__DIR__).'/app/bootstrap.php';
$user=require_permission('agenda.manage');\App\Core\Tenant::enforceActive((int)$user['tenant_id']);$t=(int)$user['tenant_id'];$error='';
$pSql="SELECT id,name,primary_professional_id FROM patients WHERE tenant_id=:t AND status='active'";$pp=['t'=>$t];if(in_array($user['role_slug'],['psychologist','supervised'],true)){$pSql.=' AND primary_professional_id=:u';$pp['u']=$user['id'];}$pSql.=' ORDER BY name';$st=db()->prepare($pSql);$st->execute($pp);$patients=$st->fetchAll();
if(in_array($user['role_slug'],['psychologist','supervised'],true))$professionals=[['id'=>$user['id'],'name'=>$user['name']]];else{$st=db()->prepare("SELECT u.id,u.name,r.slug FROM users u JOIN roles r ON r.id=u.role_id WHERE u.tenant_id=:t AND u.active=1 AND (r.slug IN ('psychologist','supervised') OR (r.slug='clinic_admin' AND u.professional_crp IS NOT NULL AND u.professional_crp<>'')) ORDER BY u.name");$st->execute(['t'=>$t]);$professionals=$st->fetchAll();}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$patient=(int)($_POST['patient_id']??0);$prof=(int)($_POST['professional_id']??0);$start=trim($_POST['starts_at']??'');$duration=max(20,min(240,(int)($_POST['duration']??50)));$modality=$_POST['modality']??'in_person';$meeting=trim($_POST['meeting_url']??'');$fee=(float)str_replace(',','.',$_POST['fee']??'0');$rec=$_POST['recurrence']??'none';$occ=max(1,min(52,(int)($_POST['occurrences']??1)));
 $pids=array_map(fn($p)=>(int)$p['id'],$patients);$profs=array_map(fn($p)=>(int)$p['id'],$professionals);
 if(!in_array($patient,$pids,true)||!in_array($prof,$profs,true)||!strtotime($start))$error='Paciente, profissional ou horário inválido.';else try{$dt=new DateTimeImmutable($start);$group=$rec==='none'?null:bin2hex(random_bytes(12));$step=$rec==='biweekly'?14:7;if($rec==='none')$occ=1;db()->beginTransaction();$ins=db()->prepare("INSERT INTO appointments(tenant_id,patient_id,professional_id,starts_at,ends_at,status,modality,meeting_url,fee,recurrence_group,public_token,created_at,updated_at) VALUES(:t,:p,:u,:s,:e,'pending',:m,:url,:fee,:g,:token,NOW(),NOW())");for($i=0;$i<$occ;$i++){$s=$dt->modify('+'.($i*$step).' days');$ins->execute(['t'=>$t,'p'=>$patient,'u'=>$prof,'s'=>$s->format('Y-m-d H:i:s'),'e'=>$s->modify('+'.$duration.' minutes')->format('Y-m-d H:i:s'),'m'=>in_array($modality,['in_person','online'],true)?$modality:'in_person','url'=>$meeting?:null,'fee'=>$fee>0?$fee:null,'g'=>$group,'token'=>bin2hex(random_bytes(32))]);}db()->commit();audit('appointment.create','appointment',null,['count'=>$occ,'professional_id'=>$prof]);flash('success',$occ.' atendimento(s) agendado(s).');redirect('agenda/index.php?date='.$dt->format('Y-m-d'));}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$error='Não foi possível salvar o agendamento.';}}
layout('Novo atendimento',function()use($patients,$professionals,$error){?>
<div class="page-head"><div><span class="eyebrow">Agenda</span><h1>Novo atendimento</h1><p>Crie uma sessão única ou uma série semanal/quinzenal.</p></div></div><form class="card form-grid" method="post"><?=csrf_field()?><?php if($error):?><div class="error-box"><?=e($error)?></div><?php endif?><div class="form-row"><div class="field"><label>Paciente</label><select name="patient_id" required><option value="">Selecione</option><?php foreach($patients as $p):?><option value="<?=$p['id']?>"><?=e($p['name'])?></option><?php endforeach?></select></div><div class="field"><label>Profissional</label><select name="professional_id" required><?php foreach($professionals as $p):?><option value="<?=$p['id']?>"><?=e($p['name'])?></option><?php endforeach?></select></div></div><div class="form-row"><div class="field"><label>Data e hora</label><input type="datetime-local" name="starts_at" required></div><div class="field"><label>Duração (minutos)</label><input type="number" name="duration" min="20" max="240" value="50"></div></div><div class="form-row"><div class="field"><label>Modalidade</label><select name="modality"><option value="in_person">Presencial</option><option value="online">On-line</option></select></div><div class="field"><label>Link Meet/Jitsi/Zoom</label><input type="url" name="meeting_url" placeholder="https://..."></div></div><div class="form-row"><div class="field"><label>Valor da sessão (opcional)</label><input name="fee" inputmode="decimal" placeholder="150,00"></div><div class="field"><label>Recorrência</label><select name="recurrence"><option value="none">Não repetir</option><option value="weekly">Semanal</option><option value="biweekly">Quinzenal</option></select></div></div><div class="field"><label>Quantidade de sessões</label><input type="number" name="occurrences" min="1" max="52" value="1"></div><div><button class="button">Salvar agendamento</button> <a class="button ghost" href="<?=e(url('agenda/index.php'))?>">Cancelar</a></div></form>
<?php },['active'=>'agenda']);
